name: solver CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          
      - name: Compile project with GCC
        run: gcc -o solver.exe field.c input.c main.c output.c search.c
        
      - name: Run tests (bat files)
        shell: cmd
        run: |
          cd tests
          call testrun.bat
          call testresult.bat
          if errorlevel 1 exit /b 1

          
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Compile project with GCC
        run: gcc -o solver field.c input.c main.c output.c search.c
        
      - name: Make test scripts executable
        run: chmod +x tests/*.sh
        
      - name: Run tests (sh files)
        run: |
          cd tests
          ./testrun.sh
          ./testresult.sh
